# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10f228e3df16145e1bf6d3f563f9e4480c7f20612c16186b9700417f615ef3da14ca9a594ace356e0a9d4d42354f9ba539c02f7c29cc50193fb05671e506066a

test:
  secret_key_base: 629fa3f922bc8893d38db7978a234a424f2df04f0e67ac2eeb0b30f3a6374fd4c27eb1f53fdde6c7638996f9a2941768dd4ee9154a7654ff58be7887bbb69c1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
